### ISSUE TITLE
Unable to build 1.3.1

### ISSUE THREAD

**Issue by relan** [err4nt/SwpieView#18]
Hi,

F-Droid maintainer here. Version 1.3.1 fails to build due to:

1. gradle/wrapper/gradle-wrapper.properties points to Gradle 3.3, while 4.1+ is required.
2. Top-level build.gradle [lacks reference to Google Maven](https://developer.android.com/studio/build/index.html#top-level) repository. Gradle cannot find Android plugin because of this. Note that Android Studio hides this issue from you, but command line tools don't.
3. lintVitalRelease task fails the whole build. Again, Android Studio excludes this task, while command line tools do not.

Steps to reproduce:

    git checkout release-1.3.1
    cd app
    gradle assembleRelease

**Comment by err4nt** [comment]
@relan Thank you very much for the report. gradle-wrapper.properties is fixed, google maven reference added back to build.gradle, lintVitalRelease and assembleRelease now pass. Tagged release-1.3.2 and bumped version in build.gradle to match.

**Comment by relan** [comment]
Thank you for quick fixes!
